- type: job
  id: Maid
  name: job-name-maid
  description: job-description-maid
  playTimeTracker: JobMaid
  requirements:
  - !type:CharacterDepartmentTimeRequirement
    department: Medical
    min: 72000 # 20 ch
  - !type:CharacterDepartmentTimeRequirement
    department: Command
    min: 72000 # 20 ch
  weight: 20
  icon: "JobIconMaid"
  supervisors: job-supervisors-hop
  canBeAntag: false
  accessGroups:
  - Maintenance
  - Command
  - Service
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MaidGear
  equipment:
    jumpsuit: ClothingUniformJumpskirtMaid
    back: ClothingBackpackSatchelFilled
    socks: ClothingUnderwearStockingsLightWhite
    shoes: ClothingShoesMaid
    ears: ClothingHeadsetCommand
    id: MaidPDA
